use_frameworks!

platform :ios, '8.0'

target 'TestPodHym_Example' do
  pod 'TestPodHym', :path => '../'

  target 'TestPodHym_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
